name: Генерация index.html из Python и C++

on:
  workflow_dispatch: # запуск вручную
  push:
    branches: [main] # запуск при пуше в main

jobs:
  build-run-save:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Клонируем репозиторий
      uses: actions/checkout@v3

    - name: 🐍 Устанавливаем Python
      run: sudo apt update && sudo apt install python3 -y

    - name: 🚀 Запускаем make_person.py
      run: python3 make_person.py

    - name: 📂 Проверяем наличие person.txt
      run: |
        if [ ! -f person.txt ]; then
          echo "❌ Файл person.txt не найден!"
          exit 1
        fi

    - name: 🛠 Устанавливаем компилятор C++
      run: sudo apt install g++ -y

    - name: 🧱 Компилируем make_html.cpp
      run: g++ make_html.cpp -o make_html

    - name: 🧾 Запускаем make_html
      run: ./make_html

    - name: 📂 Проверяем наличие index.html
      run: |
        if [ ! -f index.html ]; then
          echo "❌ Файл index.html не найден!"
          exit 1
        fi

    - name: 📄 Показываем содержимое index.html
      run: cat index.html

    - name: ⚙️ Настраиваем Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: 📤 Добавляем и пушим index.html (если изменился)
      run: |
        git add index.html
        if git diff --cached --quiet; then
          echo "🟡 Нет изменений в index.html — коммит не требуется"
        else
          git commit -m "✅ Обновлён index.html"
          git push
        fi
