name: Генерация person.txt из make_person.py

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 21 * * *' # ежедневно в 00:00 по Минску (UTC+3)

jobs:
  generate-person:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Клонируем репозиторий
      uses: actions/checkout@v3

    - name: 🐍 Устанавливаем Python
      run: sudo apt update && sudo apt install python3 -y

    - name: 🚀 Запускаем make_person.py
      run: python3 make_person.py

    - name: 📂 Проверяем наличие person.txt
      run: |
        if [ ! -f person.txt ]; then
          echo "❌ Файл person.txt не найден!"
          exit 1
        fi

    - name: 📄 Показываем содержимое person.txt
      run: cat person.txt

    - name: ⚙️ Настраиваем Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: 📤 Добавляем и пушим person.txt (если изменился)
      run: |
        git add person.txt
        if git diff --cached --quiet; then
          echo "🟡 Нет изменений в person.txt — коммит не требуется"
        else
          git commit -m "✅ Обновлён person.txt"
          git push
        fi
